title: "1n.Blog"

about: "ğŸ·ê°œë°œì ë¸”ë¡œê·¸"
markdown: kramdown
url: "https://eomtae1n.github.io"
baseurl: "/"
disqus_short_name: eomtae1n

plugins: 
  - jekyll-paginate
  - jemoji
  
paginate_path: "/page:num/"

paginate: 5

main_toc:
  - title: Home
    url: ""
  - title: About
    url: "about"
  - title: Author
    url: "author"

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
